import streamlit as st
import requests

API = "http://127.0.0.1:8000"  # URL de la API de FastAPI

# Función para generar la vista previa de la etiqueta
def generar_vista_previa():
    trabajador = st.session_state.get("trabajador_seleccionado")
    if not trabajador:
        return

    opcion = st.session_state.get("opcion_mostrar")
    producto = st.session_state.get("producto")
    cantidad = st.session_state.get("cantidad")

    valor_visible = (
        trabajador["num_orden"]
        if opcion == "Número de orden"
        else trabajador["cod_letra"]
    )

    r = requests.post(
        f"{API}/qr/preview",
        json={
            "dni": trabajador["dni"],
            "nn": valor_visible,
            "producto": producto,
            "cantidad": cantidad
        }
    )

    if r.status_code == 200 and "image" in r.headers.get("content-type", ""):
        st.session_state.preview_img = r.content
        st.session_state.preview_error = None
    else:
        st.session_state.preview_img = None
        st.session_state.preview_error = r.text


# Función para manejar la pestaña de Impresión
def pestaña_impresion():
    st.subheader("Impresión de etiquetas")
    # Aquí va la lógica de impresión y selección de trabajadores
    generar_vista_previa()
    if st.session_state.get("preview_img"):
        st.image(
            st.session_state.preview_img,
            caption="Generated by Agricola del Sur Pisco EIRL",
        )

    if st.session_state.get("preview_error"):
        st.error("Error al generar la vista previa")

    if st.button("🖨️ Imprimir etiquetas"):
        r = requests.post(
            f"{API}/qr/print",
            json={
                "dni": trabajador["dni"],
                "nn": (
                    trabajador["num_orden"]
                    if st.session_state.opcion_mostrar == "Número de orden"
                    else trabajador["cod_letra"]
                ),
                "producto": st.session_state.producto,
                "cantidad": st.session_state.cantidad,
            }
        )

        if r.status_code == 200:
            st.toast("Impresión enviada correctamente 🖨️", icon="✅")
        else:
            st.error("Error al imprimir")
